#!/bin/sh

{ echo "XIDeviceEnabled XISlaveKeyboard"; inputplug -d -c /bin/echo; } |
while read event
do
  case $event in
  XIDeviceEnabled*XISlaveKeyboard*)
    setxkbmap -layout us,il -variant dvorak, -option 'grp:ctrl_space_toggle'
    ;;
  esac
done &

dwmblocks &

~/.fehbg &

exec dwm
